action

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -81,37 +81,37 @@ jobs:
           echo "Response: $RESPONSE"
       
 
-      - name: Upload the ZIP file to Zenodo
-        env:
-          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
-          DEPOSITION_ID: ${{ env.DEPOSITION_ID }}
-        run: |
-          echo "Uploading code.zip to Zenodo deposition $DEPOSITION_ID..."
-          
-          RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/files" \
-            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
-            -H "Accept: application/json" \
-            -F "file=@code.zip;type=application/zip")
-      
-          echo "Upload response: $RESPONSE"
-      
-          if echo "$RESPONSE" | jq -e '.id' >/dev/null; then
-            echo "File uploaded successfully!"
-          else
-            echo "ERROR: Failed to upload file."
-            exit 1
-          fi
-        
       # - name: Upload the ZIP file to Zenodo
       #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
-      #   uses: zenodraft/action@0.13.3
-      #   with:
-      #     concept: ${{ steps.zenodo_deposition.outputs.concept_id }}
-      #     metadata: .zenodo.json
-      #     publish: true
-      #     sandbox: true
-      #     filenames: |
-      #       code.zip
-      #     verbose: true
+      #     ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
+      #     DEPOSITION_ID: ${{ env.DEPOSITION_ID }}
+      #   run: |
+      #     echo "Uploading code.zip to Zenodo deposition $DEPOSITION_ID..."
+          
+      #     RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/files" \
+      #       -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
+      #       -H "Accept: application/json" \
+      #       -F "file=@code.zip;type=application/zip")
+      
+      #     echo "Upload response: $RESPONSE"
+      
+      #     if echo "$RESPONSE" | jq -e '.id' >/dev/null; then
+      #       echo "File uploaded successfully!"
+      #     else
+      #       echo "ERROR: Failed to upload file."
+      #       exit 1
+      #     fi
+        
+      - name: Upload the ZIP file to Zenodo
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
+        uses: zenodraft/action@0.13.3
+        with:
+          concept: ${{ steps.zenodo_deposition.outputs.concept_id }}
+          metadata: .zenodo.json
+          publish: false
+          sandbox: true
+          filenames: |
+            code.zip
+          verbose: true
